bitcoindevkit/bdk-kyoto

- Cargo.toml
- examples/signet.rs
- examples/wallet.rs
- src/bin/example_kyoto.rs
- src/builder.rs
- src/lib.rs
In thinking about thunder's comments, this is what I drew up. Small thing, but I changed the `sync` method to `update` here to reflect what is being returned, and also to allude to the fact that this may be called throughout the lifetime of the application running. I also made a `LightClientBuilder` structure that takes a reference to the wallet. In doing so the node can be built internally by using the SPK index and the `LocalChain` tip. You'll see in the wallet example this greatly reduces the code down and makes it easier to understand what is going on. I also added a simple convenience method on the client to run the node with a new task.  Might be important to note, this abstraction mostly be for BDK and BDK FFI, as the LDK node implementation would still work with `Request` and …
> Add abstraction layer for the client

- examples/signet.rs
- examples/wallet.rs
- src/builder.rs
- src/lib.rs
with the way things have evolved, im thinking of just constructing the `Client` with a direct constructor instead of using the request flow. let me know what you think there, i added the constructor in this PR. signet example also uses it. depending on how `bdk_chain` stuff evolves or if we get any clever ideas we may also construct the `Client` directly from a `FullScanRequest`. i also use `FullScanResult` as the return type of `update` within the `Option<T>`. that way we can just apply the update directly to the wallet or the user can extract whatever fields they want
> make a new constructor, use FullScanResult

- src/lib.rs
- src/logger.rs
And always init the client's message handler with this type, i.e. no longer `Option<_>`
> impl `NodeMessageHandler` for `()`

- Cargo.toml
- examples/signet.rs
- examples/wallet.rs
- src/builder.rs
- src/lib.rs
- src/logger.rs
bumps to `beta.1`. for whatever reason when i had `alpha.13` in my `Cargo.toml` the compiler still insisted on using `beta.1`. i did a `cargo clean` and it still built `beta.` so i went ahead and upgraded. also tested new DNS in kyoto
> bump bdk_wallet and test kyoto dns

- Cargo.toml
- src/builder.rs
- src/lib.rs
- src/logger.rs
I took a first pass at revealing indexes as we apply blocks. I wasn't able to use the simple `keychains` since it uses a borrow of the `KeychainTxOutIndex` and I already have a mutable borrow out to `reveal_next_spk`. Looks a little strange and I don't think this is the right approach.
> lib: update kyoto

- src/lib.rs
I rebased the test branch and was getting an error when trying to merge the chain after a reorg but this solves it. I think adding all the recent blocks to the `LocalChain` should be the de facto anyway.
> use whole recent history

- Cargo.toml
- examples/signet.rs
- examples/wallet.rs
- src/builder.rs
- src/lib.rs
in working on the `BDKSwiftExampleWallet` it makes more sense for the caller of `update` to determine how they would like to handle logs, and not necessarily the initializer
> move logger to call site

- examples/wallet.rs
- src/builder.rs
i think this should resolve the recovery issue. developers should be specifying the lookahead if more than 25 scripts were used per keychain, so we just take that lookahead here.
cc @ValuedMammal
> feat(builder): use wallet lookahead for recovery

- src/builder.rs
- src/lib.rs
in `Client`, the only reason we have an error variant is for constructing the `Client`, which only throws one type, and sending messages, which also only throws one type of error. i removed the library error and just return those directly. the error in `builder` is now `BuilderError` and returns either a missing genesis or database error
> fix: refine error sources

- examples/wallet.rs
- src/logger.rs
we should just initialize all the `tracing` stuff for the user
cc @ValuedMammal
> Initialize `tracing` internally

- Cargo.toml
- src/lib.rs
i was going to mess around with integrating `bdk_kyoto` into `ldk-node` and ran into an issue where two different `sqlite` libraries were being built. the `rusqlite` dependency in `kyoto` is not strictly necessary so i make it an optional dependency here
> fix: add feature for `rusqlite` in `kyoto`

- examples/wallet.rs
- src/builder.rs
- src/lib.rs
I think the `PEEK_INDEX` constant was a relic of when I did not know the `Wallet` already has a lookahead via `KeychainTxOutIndex`. I think its better to assume we will always want to peek in advance whatever the user defined for their `Wallet` lookahead
> Always use lookahead in builder

- Cargo.toml
- src/builder.rs
- src/lib.rs
- tests/client.rs
fast turnaround from `0.2.0` to `0.3.0` to get ready for TABconf and library release
> lib: upgrade `kyoto` to `0.3.0`

- src/lib.rs
- src/logger.rs
I think there may be a bit of confusion with `Client::update`. I am hoping little changes like this make it clear that users may still respond to node events using this trait.
> refactor: rename `NodeMessageHandler` to `NodeEventHandler`

- src/lib.rs
- src/logger.rs
@ValuedMammal you are as good of a judge here as I am. I am trying to make the event portion of the API more visible to users. IMO the `logger` module makes sense for those specific implementations like `PrintLogger`, but I think more generally the trait might belong in the library itself.
> Move `NodeEventHandler` into `lib.rs`

- Cargo.toml
- examples/events.rs
- src/lib.rs
- src/logger.rs
- tests/client.rs
Ahead of the bindings chat I thought a little more about an event-based API as opposed to the callback style we currently have. In this draft I only have a few `Event` types, but there would be a handful more. I still don't quite know if this would be a developer experience improvement. Just looking for an opinion on this rough draft.
> Add event-based API to `Client`

- Cargo.toml
Cutting a release so bindings may take advantage of some new improvements from `kyoto`, although nothing has happened here.
> Release `0.4.0`

- examples/events.rs
- examples/signet.rs
- examples/wallet.rs
- src/builder.rs
- src/lib.rs
- tests/client.rs
As more changes crop up in the underlying client, I think it best to just expose these to the user if they are comfortable with the `clone`
I am also experiencing a UniFFI limitation where I can't broadcast transactions and update at the same time. This would enable that as well. I am thinking the "callbacks" feature might even be worth calling "uniffi" or "bindings" at this point...
Edit: I decided to rethink the architecture here. I think the main advantage of this library is to handle events form the light client in a way that is meaningful for the wallet. This means the `Client<K>` struct is almost always occupied by listening for events. To broadcast transactions or add scripts in practice, one would acquire a lock on the `Client<K>`, but this could be blocked for a while. Instead, …
> Redesign sending and receiving events

- src/lib.rs
- src/logger.rs
The user should see the reason for a failure, if there is any when broadcasting a transaction.
> Add String description for `RejectReason`

- examples/events.rs
- examples/wallet.rs
- src/builder.rs
- src/lib.rs
- tests/client.rs
Would allow for future builds that create a node for multiple wallets.
> Require `&Wallet` to `build` light client

- src/builder.rs
I must have accidentally removed the part of the patch that actually uses the trait when rebasing
> Use extension trait

- src/lib.rs
I thought this could be useful for keeping the rust docs in sync with `README.md`.
> docs: automatically include README text in lib.rs

- src/lib.rs
- tests/client.rs
Now that the crate assumes the user has one or more `Wallet`, the `update` method can actually return `Update`
> Return `Update` from `UpdateSubscriber`

- src/lib.rs
On further inspect of the `update` method, I do not think it was quite cancel-safe yet. The contract of `select!` is that either arm of the macro might be dropped. When `Drop` is called on the `update` method, we have the locally scoped variable `chain_changeset` that would be dropped. Here I move that into the struct so `Drop` may be called on the `update` future without loss of data.
> Make `update` drop-able

- src/builder.rs
- src/lib.rs
With the recent assumption that the user has a `Wallet`, the chain may be assumed as initialized with a genesis block.
> Remove custom builder error

- src/builder.rs
- src/lib.rs
Removing an unnecessary `expect` as well as mostly pointless constructor
> Remove explicit constructor for `UpdateSubscriber`

- examples/example.rs
- src/builder.rs
- src/lib.rs
There is a bit of guess-work going on when the user provides a wallet birthday. If the local chain tip is at height 0, then it is assumed that the user is trying to either 1. recover from the provided birthday 2. sync the chain from the latest checkpoint because its a new wallet. This is a little dangerous because a poor implementation may not configure the birthday, and would miss the old transactions. Also the code is convoluted and hard to reason about. To get around both of these, a `ScanType` is introduced to force the developer to specify what it is they are doing. If the implementation neglects this type and a user is trying to recover a wallet, the scan will start from height 0. To explicitly ignore old block headers and start a new wallet, one would pass `ScanType::New`
edit: I …
> Make scanning requirements explicit

- examples/example.rs
- src/builder.rs
- src/lib.rs
I noticed after the example was fully synced to the network, my computer started working overtime. I believe the loops involved in these futures are not implemented properly, as in they should actually register with the waker to be polled later. Instead they are just busy looping aimlessly and hogging cycles. Conceptually the `Receiver` type from `tokio` is not that difficult to understand, so I return them directly and inline the docs.
> Remove `LogSubscriber` and `WarningSubscriber`

- .github/workflows/ci.yml
- justfile
Adding a `check` step for 3 toolchains, simple integration test, and MSRV check that does not build the dev-dependencies
> Use `justfile` for CI steps

- .cargo/config.toml
Resolve dependnecies using the fresh v3 resolve which is msrv-aware. Allows for easy checking that the library's code is msrv-compliant while not putting any restrictions on consumers.
> build: opt in to v3 dependency resolver

- examples/example.rs
- src/lib.rs
- tests/client.rs
The optional case for `UpdateSubscriber::update` returning a `None` value can only occur if the user:
1. Syncs the wallet to the latest chain tip
2. Closes the application
3. Reopens the application and re-syncs to the same tip
While this may happen there doesn't seem to be any harm in applying the same update twice to a wallet. For developer ease-of-use, the optional case can be ignored and a repeated update can be issued in this edge case.
> Remove the optional `Update`

- Cargo.toml
- examples/example.rs
- src/lib.rs
- tests/client.rs
> This method returns None if the channel has been closed and there are
no remaining messages in the channel’s buffer. This indicates that no further values can ever be received from this Receiver.
When a channel returns `None`, we know that all sending halves of the channel have been dropped and no more messages may be received. In this case that means that the node has stopped running, as there is only a single sending halve that emits node events.
> Return error if channel reports `None`

- src/builder.rs
- src/lib.rs
From the docs:
> Checkpoints are cheaply cloneable
We can abuse that fact a bit and internally update a `CheckPoint` whenever we receive chain events. With Kyoto able to emit what was accepted to the new chain of most work, we should now be able to use `CheckPoint::insert`, which seems to have the desired behavior.
1. If the checkpoint is already there, it is ignored
2. If there is a conflicting checkpoint, the older ones at or above the height will be removed, exactly what we want for a reorg
3. Anything inserted at a greater height is appended
> Use `CheckPoint` for chain updates
